apiVersion: v1
kind: Service
metadata:
  name: training-service
  namespace: omarise
  labels:
    app: training-service
spec:
  type: ClusterIP
  selector:
    app: training-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
