apiVersion: v1
kind: Service
metadata:
  name: forum-service
  namespace: omarise
  labels:
    app: forum-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8085"
spec:
  type: ClusterIP
  selector:
    app: forum-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
